8809 fix
Inspectron/inspROLOCcontroller pull request #10
Opened 2021-03-11 18:32 UTC by tony1960

Not a perfect fix but adds stability

2021-03-11 19:09 UTC, rabidmonkeyman requested changes

2021-03-11 19:09 UTC, rabidmonkeyman commented on rolocController.cpp
> +            count++;
i honestly dont follow what the point of this queue full of bools is nor do i really understand why you only are looking for one true. but if youre only looking for a single true value then you can get rid of the count value and set retValue to true and break out of the loop

2021-03-11 19:19 UTC, dmacattack requested changes
consider implementing a hysteresis like this:

``` c++

A hysteresis is just doing a counter x many times to check if your values are changed (rather than a queue)
// create a member variable for the previous value and hysteresis count
int mHystCount;
bool mPrevPresent;

// then in the code, something like this:
bool present = rolocHardwarePresent();
if (present != mPrevPresent)
{
  if (mHystCount == 5 /*wtv max value you determine */ )
  {
     mPrevPresent = present;
  }
  else
  {
    mHysCount++; // the idea is to do several "checks" to ensure the value changes of present. dont flip flop too much
  }
}
else {
   mHystCount =0; // reset the counter
} 
```

2021-03-11 19:19 UTC, dmacattack commented on rolocController.cpp
>  /**
```suggestion
/**
```

2021-03-11 19:19 UTC, dmacattack commented on rolocController.cpp
> +            qDebug() << "roloc has been disconnected";
Lets wrap this in a debug block. If this is on a timer, you dont want to spam the console

2021-03-11 19:19 UTC, dmacattack commented on rolocController.cpp
> +
1) This functionality outside the purpose of this function, this function is called rolocHardwarePresent(). Its purpose it to check if the roloc hardware is present. Thats it. 

2) initializing the volume and signal strength should be in a state machine. And in fact it was. 

3) This logic is **always** setting the volume and mode, if the user wants to set the volume to something else, then it'll get reset in about 3seconds. 

4) you're setting the data variable again (in the lambda). This does not do what you think it does. The lambda is executed outside the scope of the original function, and setting the data has no impact on the rest of the function

for example :
``` c++
void doThing()
{
    int data = 5;
    qDebug() << "data before = " << data;
    QTimer::singleShot(2500, [&]()
    {
         qDebug() << "singleshot done, set data to 6";
         data = 6;
    });

    qDebug() << "data after = " << data;
}

// ------------- this prints -----------------
data before =  5
data after =  5
singleshot done, set data to 6
```
as you can see data doesnt print 6 ever

2021-03-11 19:19 UTC, dmacattack commented on rolocController.cpp
> +
What is this doing. you need to explain this. 
Theres a lot that is not clear here. Why is there a queue of bools, why is a queue of bools even needed, what are these magic numbers of 7 and 10?

2021-03-11 19:19 UTC, dmacattack commented on rolocController.cpp
> +bool ROLOCcontroller::evalValidity()
it looks like you're trying to implement some type of hysteresis, there are much easier ways of doing this.

2021-03-22 13:44 UTC, dmacattack requested changes
I just have some simple requests:
* add some constants to make the code more readable for the future devs (0x0200 & 0.0254)
* add parens to the math formulas to ensure what we want is being executed
* fix the member variable intialization in the ctor

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +            mBadReadCount = 0; // reset
formatting
```suggestion
         else 
         {
            mBadReadCount = 0; // reset
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +            qDebug() << "sig strength = " << mROLOCsignalStrenth; // TODO verify if is this working ?
Is this still a TODO ? Just curious

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +                float scaleOfElimination = (float)N_MULTI_LF_DEPTH_DELTA;
Lets use a C++ cast;
```suggestion
                float scaleOfElimination = static_cast<float>(N_MULTI_LF_DEPTH_DELTA);
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +                mROLOCdepthMeasurement = finalReading  * 0.0254;
whats this constant ? can we make it a constant in the anon namespace ?

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +                qDebug() << "mFrequency  mFrequency-> " << mFrequency;
lol this debug looks redundant
```suggestion
                qDebug() << "mFrequency-> " << mFrequency;
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +    depthPacket |= mFrequency;
We can simplify this to one line
```suggestion
    qint16 depthPacket = 0x0200 | mFrequency;
```

But what is the 0x0200 ? Can we add a constant for that ? its a magic number at this point

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +    mCurrentMode = ROLOC::eMODE_GET_DEPTH_MEASUREMENT;
This if block will ALWAYS have the status = -2. So you dont need to DBG_BLOCK it. In fact, I would suggest making it a warning. 

```suggestion
    if (status == BAD_DATA_READ)
    {
#if DBG_BLOCK
    qWarning() << "write status i2c failed ";
#endif
    }
    mCurrentMode = ROLOC::eMODE_GET_DEPTH_MEASUREMENT;
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.hpp
> +    bool mPrevPresent = true;
Can we move all the variable definitions to the ctor initializer list ?
Like this:
``` c++
RolocController::RolocController()
: .. 
, mBadReadCount (0)
, mPrevPresent(true)
```

2021-03-22 13:44 UTC, dmacattack commented on rolocinfopacket.cpp
> +    // ra limit the data
looks like an oopsy
```suggestion
    // range limit the data
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +                qDebug() << "Standard Dev.: " << stdDev;
you have a duplicate debug here. Lets remove one
```suggestion
                qDebug() << "sample size: " << mNumSamples;
                qDebug() << "Mean: " << mean;
                qDebug() << "Standard Dev.: " << stdDev;
```

2021-03-22 13:44 UTC, dmacattack commented on rolocController.cpp
> +                    if(!isOutOfBounds)
I dont know what math you're doing here. But can you add parenthesis to ensure your order of operations is clear? 
EG: 
``` c++
mDeptAccumulator.at(i) < ( mean - (stdDev * scaleOfElimination) );
// or
mDeptAccumulator.at(i) < ( mean - stdDev ) * scaleOfElimination );
```
I honestly dont know how the compiler does the order of operations with regards to < > 
so to be on the safe side you can tell it with some parens ?

2021-03-22 14:14 UTC, closed without merging

2021-03-22 14:14 UTC, tony1960 commented
Sorry