addresses depth and  UI  problems
Inspectron/inspROLOCcontroller pull request #11
Opened 2021-03-22 14:42 UTC by tony1960

This address 8811, 8809, 8898

2021-03-22 15:18 UTC, dmacattack requested changes

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +                qDebug() << "sample size: " << mNumSamples;
removing duplicate dbg
```suggestion
                qDebug() << "sample size: " << mNumSamples;
```

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +                float scaleOfElimination = (float)N_MULTI_LF_DEPTH_DELTA;
c++ cast
```suggestion
                float scaleOfElimination = static_cast<float>(N_MULTI_LF_DEPTH_DELTA);
```

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +                    quint8 isOutOfBounds = isLessThanLowerBound || isGreaterThanUpperBound;
can you add parens around your math to ensure the order of ops is correct?

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +                mROLOCdepthMeasurement = finalReading  * 0.0254;
can you make this a constant ?

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +                qDebug() << "mFrequency  mFrequency-> " << mFrequency;
duplicate dbg
```suggestion
                qDebug() << " mFrequency-> " << mFrequency;
```

2021-03-22 15:18 UTC, dmacattack commented on rolocController.cpp
> +    int status = m_i2cBus.i2c_writeWord(mI2cAddr, ROLOC::eCMD_INFO, depthPacket);
simplify the equation. can you make this 0x0200 a constant ?

```suggestion
    qint16 depthPacket = 0x0200 | mFrequency ;
    int status = m_i2cBus.i2c_writeWord(mI2cAddr, ROLOC::eCMD_INFO, depthPacket);
```

2021-03-22 15:18 UTC, dmacattack commented on rolocController.hpp
> +    bool mPrevPresent = true;
lets put these in the ctors initializer list

2021-03-22 15:47 UTC, rabidmonkeyman requested changes
i just want to point out that every time i make a release for i3000, this roloccontroller is always spamming the console with worthless prints. this thing is sporadically used as is, we dont need to know every time an i2c transaction with it failed because its not present, etc. please keep that in mind when working on this component. if you run this application, will it print 5 lines to the console every 5 seconds?

2021-03-22 15:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +           if (mBadReadCount == MAX_BAD_READS)
should this be ">="?

2021-03-22 15:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +        else
is this an else if? or is it a nested if inside the else statement? the formatting is poor

2021-03-22 15:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +            if(mNumSamples > N_MULTI_LF_DEPTH_SAMPLE)
should this also be ">="?

2021-03-22 15:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +
so much extra new lines

2021-03-22 15:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +    depthPacket = 0x0200;
magic number

2021-03-22 15:51 UTC, tony1960 commented on rolocController.cpp
> +                qDebug() << "sample size: " << mNumSamples;
done

2021-03-22 15:51 UTC, tony1960 commented on rolocController.cpp
> +                    quint8 isOutOfBounds = isLessThanLowerBound || isGreaterThanUpperBound;
done

2021-03-22 15:51 UTC, tony1960 commented on rolocController.cpp
> +                mROLOCdepthMeasurement = finalReading  * 0.0254;
Yes

2021-03-22 15:51 UTC, tony1960 commented on rolocController.cpp
> +                qDebug() << "mFrequency  mFrequency-> " << mFrequency;
DOne

2021-03-22 15:52 UTC, tony1960 commented on rolocController.cpp
> +    int status = m_i2cBus.i2c_writeWord(mI2cAddr, ROLOC::eCMD_INFO, depthPacket);
Yes

2021-03-22 15:53 UTC, tony1960 commented on rolocController.hpp
> +    bool mPrevPresent = true;
Done

2021-03-22 15:58 UTC, tony1960 commented on rolocController.cpp
> +            if(mNumSamples > N_MULTI_LF_DEPTH_SAMPLE)
We chatted about this

2021-03-22 15:59 UTC, tony1960 commented on rolocController.cpp
> +
Yeah yeah fixed

2021-03-22 15:59 UTC, tony1960 commented on rolocController.cpp
> +    depthPacket = 0x0200;
Done

2021-03-25 14:28 UTC, dmacattack commented
@tony1960 you requested us to review again, but you didnt push any new changes. Did you forget to push new changes?
Remember you can make code changes and do another git push origin <branchname>

2021-03-25 14:34 UTC, tony1960 commented
ok I got them all

2021-03-25 14:39 UTC, tony1960 commented on rolocController.cpp
> +                    quint8 isOutOfBounds = isLessThanLowerBound || isGreaterThanUpperBound;
as per discussion, this has not been touched

2021-03-25 14:39 UTC, tony1960 commented on rolocController.cpp
> +                float scaleOfElimination = (float)N_MULTI_LF_DEPTH_DELTA;
as per discussion, this has not been touched

2021-03-25 14:40 UTC, tony1960 commented on rolocController.cpp
> +                qDebug() << "mFrequency  mFrequency-> " << mFrequency;
removed

2021-03-25 14:40 UTC, tony1960 commented on rolocController.cpp
> +           if (mBadReadCount == MAX_BAD_READS)
sure

2021-03-25 14:40 UTC, tony1960 commented on rolocController.cpp
> +            if(mNumSamples > N_MULTI_LF_DEPTH_SAMPLE)
as per discussion, this has not been touched

2021-03-25 14:43 UTC, dmacattack approved these changes
Just a few changes
* turn off the dbg_block
* looks like theres a copy paste error on line 529
* can you delete the qCritical code in the ctor

2021-03-25 14:43 UTC, dmacattack commented on rolocController.cpp
> +#define DBG_BLOCK 1
Lets change this to 0 before merging

2021-03-25 14:43 UTC, dmacattack commented on rolocController.cpp
>      qCritical() << "------------------------";
Can you do me a favor ? I know this isnt your code. It was mine when the address was causing problems with linux. 

Can you delete this ? I dont think we need this anymore

2021-03-25 14:43 UTC, dmacattack commented on rolocController.cpp
> + * the ROLOC doesnt get mixed uponImageEdited
huh ?

2021-03-25 14:47 UTC, rabidmonkeyman requested changes

2021-03-25 14:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +#define DBG_BLOCK 1
you gotta leave this off before you merge

2021-03-25 14:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +    const int    INCHES_TO_METERS                           = 0.0254;
int? this should be a float or a double

2021-03-25 14:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +            if(mNumSamples > N_MULTI_LF_DEPTH_SAMPLE)
we chatted about this?

2021-03-25 14:47 UTC, rabidmonkeyman commented on rolocController.cpp
> +                float scaleOfElimination = static_cast<float>(N_MULTI_LF_DEPTH_DELTA);
im not sure what the point of this variable is? why not just replace this variable with the constant in the equations its used in

2021-03-25 15:05 UTC, dmacattack commented on rolocController.cpp
> +    const int    INCHES_TO_METERS                           = 0.0254;
good point. this will make this constant zero with the integer truncation.

2021-03-25 18:57 UTC, dmacattack approved these changes

2021-03-25 20:43 UTC, rabidmonkeyman approved these changes

2021-03-25 20:43 UTC, merged